// @desc: Logic implementation for different client handling 



// The diea is to have a new hub connection instance with the
// SessionKey generated by the keygen as a method name
//that is going to prevent a broadcast from getting data
// that is not intended for you 
// well you'll have to go through signalr  code 

// signalr sends the session token as headers which you can 
// retrive on the server using[server side] 
//var connection = new Connection("http://signalr/");
//connection.Headers.Add("custom-header", "value");
// [client javascript]




module.exports = function (SessionKey, SignalR) {
    
    var listener = function () {
        
        // Client - Server hub connection  
        SignalR.hub(SessionKey, {
            Send : function (name, message) {
                // @note: This type of 
                this.clients.all.invoke('AddMessage').withArgs([name, message]);
                console.log('send:' + message);
            }
        });

    }
    
    
    // Define constructor 
    var ClientConnection = function () {
        this.setListener = listener;
    };
    
    return ClientConnection;
}


